In [16]:
import pandas as pd

In [5]:
df = pd.read_csv("AppleGenotypes.csv", index_col="code")
df

,Exeter Cross_2291,Michelin,Lizzie,Amelia,Jane,Willy,Plymouth_2263,Connie_2270,Debbie_2292,Sweet Alford,...,Wimple Wonder,Merton Charm,Malus sylvestris_1,Helen_E3,Admirals Wildling,King's Favourite,Evereste,Beauty of Bath,Merton Russet,Helen_E4
code,,,,,,,,,,,,,,,,,,,,,
MDC012883.431_60874,0,0,0,0,0,0,0,0,0,1,...,0,0,2,0,0,1,0,0,0,0
MDC053039.000_4571,0,1,1,1,1,1,0,1,0,0,...,0,0,0,0,1,1,0,0,0,0
MDC053607.000_15047,2,-1,-1,0,0,0,0,0,-1,1,...,1,1,1,1,0,2,2,1,0,1
MDC018253.85_16080,0,0,1,1,1,1,0,1,1,0,...,1,1,0,0,0,0,1,0,0,0
MDC040338.15_2126,0,0,0,0,0,0,1,0,0,0,...,0,1,0,1,0,0,0,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MDC052345.000_19850,2,2,2,1,2,1,1,1,2,1,...,1,1,1,2,1,1,1,1,1,2
MDC052509.000_8600,0,1,0,0,0,0,1,0,0,1,...,1,0,0,0,0,1,1,0,0,0
MDC000971.392_11516,0,1,1,2,1,1,1,1,1,1,...,0,1,1,0,1,1,-1,0,1,0
MDC054291.001_23634,2,2,2,2,2,2,1,2,2,2,...,2,2,2,2,2,2,2,2,2,2
MDC001638.431_5367,0,2,1,0,0,0,1,0,1,1,...,1,1,1,1,2,1,-1,1,1,1

In [7]:
df = df.replace("AB", 1).replace("A", 0).replace("B", 2)
df

,Exeter Cross_2291,Michelin,Lizzie,Amelia,Jane,Willy,Plymouth_2263,Connie_2270,Debbie_2292,Sweet Alford,...,Wimple Wonder,Merton Charm,Malus sylvestris_1,Helen_E3,Admirals Wildling,King's Favourite,Evereste,Beauty of Bath,Merton Russet,Helen_E4
code,,,,,,,,,,,,,,,,,,,,,
MDC012883.431_60874,0,0,0,0,0,0,0,0,0,1,...,0,0,2,0,0,1,0,0,0,0
MDC053039.000_4571,0,1,1,1,1,1,0,1,0,0,...,0,0,0,0,1,1,0,0,0,0
MDC053607.000_15047,2,-1,-1,0,0,0,0,0,-1,1,...,1,1,1,1,0,2,2,1,0,1
MDC018253.85_16080,0,0,1,1,1,1,0,1,1,0,...,1,1,0,0,0,0,1,0,0,0
MDC040338.15_2126,0,0,0,0,0,0,1,0,0,0,...,0,1,0,1,0,0,0,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MDC052345.000_19850,2,2,2,1,2,1,1,1,2,1,...,1,1,1,2,1,1,1,1,1,2
MDC052509.000_8600,0,1,0,0,0,0,1,0,0,1,...,1,0,0,0,0,1,1,0,0,0
MDC000971.392_11516,0,1,1,2,1,1,1,1,1,1,...,0,1,1,0,1,1,-1,0,1,0
MDC054291.001_23634,2,2,2,2,2,2,1,2,2,2,...,2,2,2,2,2,2,2,2,2,2
MDC001638.431_5367,0,2,1,0,0,0,1,0,1,1,...,1,1,1,1,2,1,-1,1,1,1

In [35]:
def clean(x):
    try:
        x = int(x)
        if x >= 0 and x <= 2:
            return x
    except Exception:
        pass

    return "x"

df = df.applymap(
    lambda x: clean(x)
)
df

,Exeter Cross_2291,Michelin,Lizzie,Amelia,Jane,Willy,Plymouth_2263,Connie_2270,Debbie_2292,Sweet Alford,...,Wimple Wonder,Merton Charm,Malus sylvestris_1,Helen_E3,Admirals Wildling,King's Favourite,Evereste,Beauty of Bath,Merton Russet,Helen_E4
code,,,,,,,,,,,,,,,,,,,,,
MDC012883.431_60874,0,0,0,0,0,0,0,0,0,1,...,0,0,2,0,0,1,0,0,0,0
MDC053039.000_4571,0,1,1,1,1,1,0,1,0,0,...,0,0,0,0,1,1,0,0,0,0
MDC053607.000_15047,2,x,x,0,0,0,0,0,x,1,...,1,1,1,1,0,2,2,1,0,1
MDC018253.85_16080,0,0,1,1,1,1,0,1,1,0,...,1,1,0,0,0,0,1,0,0,0
MDC040338.15_2126,0,0,0,0,0,0,1,0,0,0,...,0,1,0,1,0,0,0,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
MDC052345.000_19850,2,2,2,1,2,1,1,1,2,1,...,1,1,1,2,1,1,1,1,1,2
MDC052509.000_8600,0,1,0,0,0,0,1,0,0,1,...,1,0,0,0,0,1,1,0,0,0
MDC000971.392_11516,0,1,1,2,1,1,1,1,1,1,...,0,1,1,0,1,1,x,0,1,0
MDC054291.001_23634,2,2,2,2,2,2,1,2,2,2,...,2,2,2,2,2,2,2,2,2,2
MDC001638.431_5367,0,2,1,0,0,0,1,0,1,1,...,1,1,1,1,2,1,x,1,1,1